/**
 * Ledger — manually recorded revenue & expenses.
 *
 * ─── Naming note ────────────────────────────────────────────────────
 * This module was specced as "Ad Hoc Revenue / Ad Hoc Expenses". The
 * codebase already uses "ad hoc" for something else entirely — the
 * per-session Match Practice purchase mode (`CorporateBatchMode`, once
 * literally `ADHOC`, renamed to `REGULAR`) — so reusing the phrase for
 * hand-entered accounting would collide on the same dashboard. The
 * money here isn't "ad hoc" either; it's ordinary revenue and ordinary
 * operating costs that simply weren't generated by the booking engine.
 *
 * So the module is the **Ledger**, and its two sides are:
 *   REVENUE → "Manual Revenue"  (vs. system-generated booking/package)
 *   EXPENSE → "Expenses"
 *
 * Everything user-visible uses those words; nothing says "ad hoc".
 * ────────────────────────────────────────────────────────────────────
 *
 * Both sides live in one `LedgerEntry` table discriminated by `kind`,
 * with kind-specific columns nullable at the DB level. This module is
 * the single place that defines what a valid entry of each kind looks
 * like — labels, the expense subcategory catalog, and the Zod schemas
 * shared by the create and update routes.
 */

import { z } from 'zod';

export type LedgerKind = 'REVENUE' | 'EXPENSE';

export const LEDGER_KINDS = ['REVENUE', 'EXPENSE'] as const;

/** What a Manual Revenue entry was earned from. */
export const LEDGER_REVENUE_CATEGORIES = [
  'MACHINE',
  'NET',
  'SIDEARM',
  'COACHING',
  'FULL_COURT',
  'MATCH_PRACTICE',
  'OTHER',
] as const;
export type LedgerRevenueCategoryId = (typeof LEDGER_REVENUE_CATEGORIES)[number];

/**
 * Labels mirror the booking categories the rest of the admin panel
 * shows (see `CATEGORY_LABELS` on the dashboard), so a manual entry
 * reads the same as the booking it stands in for.
 */
export const LEDGER_REVENUE_CATEGORY_LABELS: Record<LedgerRevenueCategoryId, string> = {
  MACHINE: 'Bowling Machine',
  NET: 'Cricket Nets',
  SIDEARM: 'Side Arm',
  COACHING: 'Personal Coaching',
  FULL_COURT: 'Full Indoor Court',
  MATCH_PRACTICE: 'Match Practice',
  OTHER: 'Other / Miscellaneous',
};

export const LEDGER_EXPENSE_CATEGORIES = [
  'REPAIRS_MAINTENANCE',
  'BALLS',
  'STAFF_PAYMENTS',
  'UTILITIES_CONSUMABLES',
  'MISCELLANEOUS',
] as const;
export type LedgerExpenseCategoryId = (typeof LEDGER_EXPENSE_CATEGORIES)[number];

export const LEDGER_EXPENSE_CATEGORY_LABELS: Record<LedgerExpenseCategoryId, string> = {
  REPAIRS_MAINTENANCE: 'Repairs & Maintenance',
  BALLS: 'Ball Expenses',
  STAFF_PAYMENTS: 'Staff Payments',
  UTILITIES_CONSUMABLES: 'Utilities & Consumables',
  MISCELLANEOUS: 'Miscellaneous',
};

/**
 * Expense subcategories, per category. Stored as a TEXT code on the row
 * rather than a Postgres enum, so this catalog can grow without a
 * migration — but it IS validated against, so a typo can't create a
 * silent one-off bucket that breaks grouping in reports.
 *
 * Every category ends with `OTHER` so nothing is unclassifiable; the
 * free-text Description carries the specifics in that case.
 */
export const LEDGER_EXPENSE_SUBCATEGORIES: Record<
  LedgerExpenseCategoryId,
  ReadonlyArray<{ value: string; label: string }>
> = {
  REPAIRS_MAINTENANCE: [
    { value: 'NET_REPAIR', label: 'Net Repair' },
    { value: 'CEMENT_REPAIR', label: 'Cement Repair' },
    { value: 'MAT_REPAIR', label: 'Mat Repair' },
    { value: 'TURF_REPAIR', label: 'Turf Repair' },
    { value: 'MACHINE_REPAIR', label: 'Machine Repair' },
    { value: 'EQUIPMENT_REPAIR', label: 'Equipment Repair' },
    { value: 'OTHER', label: 'Other Repair / Maintenance' },
  ],
  BALLS: [
    { value: 'LEATHER_BALL', label: 'Leather Ball' },
    { value: 'TENNIS_BALL', label: 'Tennis Ball' },
    { value: 'OTHER', label: 'Other Balls' },
  ],
  STAFF_PAYMENTS: [
    { value: 'SIDEARM_SPECIALIST', label: 'Sidearm Specialist Payment' },
    { value: 'COACHING_STAFF', label: 'Coaching Staff Payment' },
    { value: 'GROUND_STAFF', label: 'Ground Staff Payment' },
    { value: 'OPERATOR', label: 'Operator Payment' },
    { value: 'OTHER', label: 'Other Staff Payment' },
  ],
  UTILITIES_CONSUMABLES: [
    { value: 'ELECTRICITY', label: 'Electricity' },
    { value: 'DRINKING_WATER', label: 'Drinking Water' },
    { value: 'INTERNET', label: 'Internet / Phone' },
    { value: 'CONSUMABLES', label: 'Miscellaneous Consumables' },
    { value: 'OTHER', label: 'Other Utility' },
  ],
  // Miscellaneous is the escape hatch — it has no meaningful split, so
  // the form hides the subcategory picker entirely for it.
  MISCELLANEOUS: [],
};

/** Human label for a stored subcategory code, or '' when unset. */
export function expenseSubcategoryLabel(
  category: LedgerExpenseCategoryId | null | undefined,
  value: string | null | undefined,
): string {
  if (!category || !value) return '';
  const found = LEDGER_EXPENSE_SUBCATEGORIES[category]?.find((s) => s.value === value);
  return found?.label ?? value;
}

/** True when the category has subcategories to choose from. */
export function categoryHasSubcategories(category: LedgerExpenseCategoryId): boolean {
  return (LEDGER_EXPENSE_SUBCATEGORIES[category]?.length ?? 0) > 0;
}

export const LEDGER_PAYMENT_METHODS = [
  'CASH',
  'TOPLAY_SCANNER',
  'PLAYORBIT_SCANNER',
  'UPI',
  'CARD',
  'BANK_TRANSFER',
  'ONLINE',
  'OTHER',
] as const;
export type LedgerPaymentMethodId = (typeof LEDGER_PAYMENT_METHODS)[number];

export const LEDGER_PAYMENT_METHOD_LABELS: Record<LedgerPaymentMethodId, string> = {
  CASH: 'Cash',
  TOPLAY_SCANNER: 'Toplay Scanner',
  PLAYORBIT_SCANNER: 'PlayOrbit Scanner',
  UPI: 'UPI',
  CARD: 'Card',
  BANK_TRANSFER: 'Bank Transfer',
  ONLINE: 'Online (Razorpay)',
  OTHER: 'Other',
};

// ─── Validation ──────────────────────────────────────────────────────

const dateString = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}$/, 'Date must be YYYY-MM-DD')
  .refine((v) => !Number.isNaN(Date.parse(`${v}T00:00:00.000Z`)), 'Invalid date');

const timeString = z
  .string()
  .regex(/^([01]\d|2[0-3]):[0-5]\d$/, 'Time must be HH:MM (24-hour)');

const optionalText = (max: number) =>
  z
    .string()
    .trim()
    .max(max)
    .optional()
    .nullable()
    .transform((v) => (v ? v : null));

/**
 * Shared columns. `recordedById` is intentionally absent — it is always
 * taken from the session server-side, never from the request body.
 */
const BaseFields = {
  amount: z
    .number({ message: 'Amount is required' })
    .finite('Amount must be a number')
    .positive('Amount must be greater than 0')
    .max(10_000_000, 'Amount looks too large'),
  entryDate: dateString,
  entryTime: timeString,
  paymentMethod: z.enum(LEDGER_PAYMENT_METHODS),
  remarks: optionalText(1000),
};

const RevenueEntrySchema = z.object({
  kind: z.literal('REVENUE'),
  revenueCategory: z.enum(LEDGER_REVENUE_CATEGORIES),
  customerName: z.string().trim().min(1, 'Customer name is required').max(200),
  // The session being paid for. Optional: a miscellaneous sale (a ball,
  // a kit rental) has no session behind it.
  serviceDate: dateString.optional().nullable(),
  serviceTime: timeString.optional().nullable(),
  ...BaseFields,
});

const ExpenseEntrySchema = z
  .object({
    kind: z.literal('EXPENSE'),
    expenseCategory: z.enum(LEDGER_EXPENSE_CATEGORIES),
    expenseSubcategory: z.string().trim().max(60).optional().nullable(),
    description: z.string().trim().min(1, 'Description is required').max(500),
    paidTo: optionalText(200),
    ...BaseFields,
  })
  .superRefine((val, ctx) => {
    const options = LEDGER_EXPENSE_SUBCATEGORIES[val.expenseCategory] ?? [];
    if (options.length === 0) {
      // MISCELLANEOUS: no subcategory exists, so anything sent is wrong.
      return;
    }
    if (!val.expenseSubcategory) {
      ctx.addIssue({
        code: 'custom',
        path: ['expenseSubcategory'],
        message: 'Subcategory is required for this expense category',
      });
      return;
    }
    if (!options.some((o) => o.value === val.expenseSubcategory)) {
      ctx.addIssue({
        code: 'custom',
        path: ['expenseSubcategory'],
        message: 'Unknown subcategory for this expense category',
      });
    }
  });

/**
 * A whole entry, discriminated by `kind`. Used for both create and
 * update — an edit sends the complete entry, which keeps the per-kind
 * required-field rules enforceable (a partial PATCH could otherwise
 * strip a required column past validation).
 */
export const LedgerEntryInputSchema = z.discriminatedUnion('kind', [
  RevenueEntrySchema,
  ExpenseEntrySchema,
]);

export type LedgerEntryInput = z.infer<typeof LedgerEntryInputSchema>;

/**
 * Normalize validated input into the column set to persist. Columns
 * belonging to the *other* kind are explicitly nulled so switching an
 * entry's kind on edit can never leave stale data behind.
 */
export function toLedgerColumns(input: LedgerEntryInput) {
  const shared = {
    kind: input.kind,
    amount: input.amount,
    entryDate: new Date(`${input.entryDate}T00:00:00.000Z`),
    entryTime: input.entryTime,
    paymentMethod: input.paymentMethod,
    remarks: input.remarks ?? null,
  };

  if (input.kind === 'REVENUE') {
    return {
      ...shared,
      revenueCategory: input.revenueCategory,
      customerName: input.customerName,
      serviceDate: input.serviceDate ? new Date(`${input.serviceDate}T00:00:00.000Z`) : null,
      serviceTime: input.serviceTime ?? null,
      expenseCategory: null,
      expenseSubcategory: null,
      description: null,
      paidTo: null,
    };
  }

  return {
    ...shared,
    revenueCategory: null,
    customerName: null,
    serviceDate: null,
    serviceTime: null,
    expenseCategory: input.expenseCategory,
    // MISCELLANEOUS has no subcategories — drop anything sent for it.
    expenseSubcategory: categoryHasSubcategories(input.expenseCategory)
      ? (input.expenseSubcategory ?? null)
      : null,
    description: input.description,
    paidTo: input.paidTo ?? null,
  };
}

/** Category label for an entry of either kind, for tables and CSVs. */
export function ledgerCategoryLabel(entry: {
  kind: LedgerKind;
  revenueCategory?: string | null;
  expenseCategory?: string | null;
}): string {
  if (entry.kind === 'REVENUE') {
    const c = entry.revenueCategory as LedgerRevenueCategoryId | null | undefined;
    return c ? (LEDGER_REVENUE_CATEGORY_LABELS[c] ?? c) : '';
  }
  const c = entry.expenseCategory as LedgerExpenseCategoryId | null | undefined;
  return c ? (LEDGER_EXPENSE_CATEGORY_LABELS[c] ?? c) : '';
}
